on:
  push:
    branches: [ main ]
    paths: frontend/*
  pull_request:
    branches: [ main ]
    paths: frontend/*
  workflow_dispatch:

env: 
  AWS_REGION: "us-east-2"
  S3_BUCKET_NAME: "resume.gagelara"
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
  CLOUDFRONT_URL: ${{ secrets.CLOUDFRONT_URL }}

permissions:
  id-token: write
  contents: read

concurrency:
  group: "frontend"
  cancel-in-progress: false

jobs:
  build hugo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: npm ci

