on:
  push:
    branches: [ main ]
    paths: infra/prod/*
  pull_request:
    branches: [ main ]
    paths: infra/prod/*
env: 
  AWS_REGION : "us-east-2" 

permissions:
      id-token: write   
      contents: read    

concurrency:
  group: "infra"
  cancel-in-progress: false

jobs:
  Apply-Terraform-to-Poduction:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./prod
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0

        with:
          role-to-assume: ${{ secrets.AWS_ROLE }} 
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Init Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
            TF_INPUT: false